services:
  quiz-llm-api:
    build: .
    container_name: quiz-llm-api
    ports:
      - "8003:8003"
    environment:
      # 환경 변수들 (.env 파일에서 로드)
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=${LOG_LEVEL:-INFO}
    env_file:
      - .env  # 환경 변수 파일
    volumes:
      # 개발 시 코드 변경사항 실시간 반영 (선택사항)
      - ./src:/app/src:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8003/docs"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 개발용 서비스 (코드 변경사항 실시간 반영)
  quiz-llm-dev:
    build: .
    container_name: quiz-llm-dev
    ports:
      - "8004:8003"
    environment:
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - LOG_LEVEL=DEBUG
    env_file:
      - .env
    volumes:
      - .:/app
    command: ["uv", "run", "uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8003", "--reload"]
    profiles:
      - dev
